Cleaning for Ppro

In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv(r"C:\Users\abba\Desktop\DS Projects\AMAC-Rental-Intelligence-Dashboard\Data\raw\ppro_raw_listings.csv")
df.head()

,page,Price,Location,Bedrooms,List Date
0,1,"₦ 35,000,000/year",Diplomatic Zone Asokoro Abuja,Furnished 5 Bedroom Detached Duplex,"Updated 09 Feb 2026, Added 01 Jan 2026"
1,1,"₦ 40,000,000/year",Asokoro District Abuja Diplomatic Zone Asokoro...,6 Bedroom Mansion With 2room Bq,"Updated 09 Feb 2026, Added 22 Dec 2025"
2,1,"₦ 13,000,000/year",Asokoro Abuja Diplomatic Zone Asokoro Abuja,3 Bedroom Block Of Flat,"Updated 09 Feb 2026, Added 11 Dec 2025"
3,1,"₦ 18,000,000/year",Guzape District Abuja Diplomatic Zone Guzape A...,4 Bedroom Terrace Duplex With Bq,"Updated 09 Feb 2026, Added 22 Dec 2025"
4,1,"₦ 25,000,000/year","Diplomatic Zone, Guzape Abuja",Newly Built 4 Bedroom Terrace Duplex With Bq,"Updated 09 Feb 2026, Added 10 Dec 2025"

In [3]:
df = df.drop(['page', 'List Date'], axis=1)
df.head()

,Price,Location,Bedrooms
0,"₦ 35,000,000/year",Diplomatic Zone Asokoro Abuja,Furnished 5 Bedroom Detached Duplex
1,"₦ 40,000,000/year",Asokoro District Abuja Diplomatic Zone Asokoro...,6 Bedroom Mansion With 2room Bq
2,"₦ 13,000,000/year",Asokoro Abuja Diplomatic Zone Asokoro Abuja,3 Bedroom Block Of Flat
3,"₦ 18,000,000/year",Guzape District Abuja Diplomatic Zone Guzape A...,4 Bedroom Terrace Duplex With Bq
4,"₦ 25,000,000/year","Diplomatic Zone, Guzape Abuja",Newly Built 4 Bedroom Terrace Duplex With Bq

In [4]:
#Create Property type column from messy 'Bedrooms' column and clean 'Bedrooms' column
df['Bedrooms(s)'] = df['Bedrooms'].str.extract(r'(\d+)')
df['Property Type'] = df['Bedrooms'].str.replace(r'\d+\s*Bedroom\s*', '', regex=True).str.strip()
df.head()

,Price,Location,Bedrooms,Bedrooms(s),Property Type
0,"₦ 35,000,000/year",Diplomatic Zone Asokoro Abuja,Furnished 5 Bedroom Detached Duplex,5,Furnished Detached Duplex
1,"₦ 40,000,000/year",Asokoro District Abuja Diplomatic Zone Asokoro...,6 Bedroom Mansion With 2room Bq,6,Mansion With 2room Bq
2,"₦ 13,000,000/year",Asokoro Abuja Diplomatic Zone Asokoro Abuja,3 Bedroom Block Of Flat,3,Block Of Flat
3,"₦ 18,000,000/year",Guzape District Abuja Diplomatic Zone Guzape A...,4 Bedroom Terrace Duplex With Bq,4,Terrace Duplex With Bq
4,"₦ 25,000,000/year","Diplomatic Zone, Guzape Abuja",Newly Built 4 Bedroom Terrace Duplex With Bq,4,Newly Built Terrace Duplex With Bq

In [8]:
df = df.drop(['Bedrooms'], axis = 1)
df.head()

,Price,Location,Bedrooms(s),Property Type
0,"₦ 35,000,000/year",Diplomatic Zone Asokoro Abuja,5,Furnished Detached Duplex
1,"₦ 40,000,000/year",Asokoro District Abuja Diplomatic Zone Asokoro...,6,Mansion With 2room Bq
2,"₦ 13,000,000/year",Asokoro Abuja Diplomatic Zone Asokoro Abuja,3,Block Of Flat
3,"₦ 18,000,000/year",Guzape District Abuja Diplomatic Zone Guzape A...,4,Terrace Duplex With Bq
4,"₦ 25,000,000/year","Diplomatic Zone, Guzape Abuja",4,Newly Built Terrace Duplex With Bq

In [9]:
df.to_csv(r"C:\Users\abba\Desktop\DS Projects\AMAC-Rental-Intelligence-Dashboard\Data\messy.csv")

In [ ]:
import numpy as np

# 1. Create the categorization logic
def prop_category(text):
    # Convert everything to lowercase to make matching easier
    text = str(text).lower()
    
    # Priority 1: Identify and flag non-residential or unwanted properties first
    non_residential_keywords = ['office', 'warehouse', 'shop', 'land', 'commercial', 'plaza', 'store', 'hotel']
    if any(word in text for word in non_residential_keywords):
        return np.nan  # Tag as NaN so we can drop it easily later

    # Priority 2: Categorize as Bungalow
    if 'bungalow' in text:
        return 'Bungalow'

    # Priority 3: Categorize as Duplex 
    # (Including 'mansion' and 'terrace' here since they function as duplexes in this market)
    duplex_keywords = ['duplex', 'mansion', 'terrace', 'penthouse']
    if any(word in text for word in duplex_keywords):
        return 'Duplex'

    # Priority 4: Categorize as Apartment
    apartment_keywords = ['flat', 'apartment', 'room', 'studio']
    if any(word in text for word in apartment_keywords):
        return 'Apartment'

    # Catch-all: If it doesn't match anything above, flag it to be dropped
    return np.nan

# 2. Apply the function to create the new column
df['Property Category'] = df['Property Type'].apply(prop_category)

# 3. Drop all rows that were tagged as non-residential or unmatched (NaN)
df_cleaned = df.dropna(subset=['Property Category']).reset_index(drop=True)

# Let's check the results
print(df_cleaned[['Property Type', 'Property Category']].head())

In [ ]:
prop_types = ['Duplex', 'Apartment', 'Bungalow']

In [ ]:
#Extract Property categories from property type column
df['Property Category'] =